Traceback (most recent call last):
  File "../main.py", line 160, in <module>
    main()
  File "../main.py", line 148, in main
    avg_loss,top1,top5 = test_model(config,test_ds)
  File "/workspace/tfg_hhernandez/utils/evaluate.py", line 71, in test_model
    raise Exception ("no checkpoint found at '{}'".format(config.classifier.test_weights_path))
Exception: no checkpoint found at '/results/multimodal/timesformer/objs_text/best_epoch.pt'
